service: haverim-lerefua
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket

# custom:
#  profiles:
#    dev: dev
#    prod: prod

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  deploymentBucket:
    name: haverim-app-serverless
#  profile: ${self:custom.profiles.${sls:stage}}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'


