service: haverim-lerefua
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

resources:
  - ${file(infra/cloud-front.yml)}
